function out(m, v) {
    console.log(m, v);
}

// out('5 == 5',5 == 5);
// out('"apple" == "apple"',"apple" == "apple");
// out('"5" == 5',"5" == 5);
// out('5 == "5"',5 == "5");
// out('0 == false',0 == false);
// out('0 == null',0 == null);
// out('0 == undefined',0 == undefined);
// out('0 == !!null',0 == !!null);
// out('0 == !!undefined',0 == !!undefined);
// out('null == undefined',null == undefined);
// var number1 = new Number(2);
// var number2 = new Number(2);
// out('number1 == 2',number1 == 2);
// out('number1 == number2',number1 == number2);
// var obj1 = {name: "Bob"};
// var obj2 = {name: "Bob"};
// out('obj1 == obj2',obj1 == obj2);
// out('obj2 == obj2',obj2 == obj2);
// var str1 = "orange";
// var str2 = String("orange");
// var str3 = new String("orange");
// var str4 = new String("orange");
// out('str1 == str2',str1 == str2);
// out('str1 == str3',str1 == str3);
// out('str2 == str3',str2 == str3);
// out('str3 == str4',str3 == str4);
// out('str4 == str4',str4 == str4);
// var dt = new Date("November 24, 2020 17:41:00");
// var ds = dt.toString();
// out('dt == ds',dt == ds);

// out('5 === 5',5 === 5);
// out('"apple" === "apple"',"apple" === "apple");
// out('"5" === 5',"5" === 5);
// out('5 === "5"',5 === "5");
// out('0 === false',0 === false);
// out('0 === null',0 === null);
// out('0 === undefined',0 === undefined);
// out('0 === !!null',0 === !!null);
// out('0 === !!undefined',0 === !!undefined);
// out('null === undefined',null === undefined);
// var number1 = new Number(2);
// var number2 = new Number(2);
// out('number1 === 2',number1 === 2);
// out('number1 === number2',number1 === number2);
// var obj1 = {name: "Bob"};
// var obj2 = {name: "Bob"};
// out('obj1 === obj2',obj1 === obj2);
// out('obj2 === obj2',obj2 === obj2);
// var str1 = "orange";
// var str2 = String("orange");
// var str3 = new String("orange");
// var str4 = new String("orange");
// out('str1 === str2',str1 === str2);
// out('str1 === str3',str1 === str3);
// out('str2 === str3',str2 === str3);
// out('str3 === str4',str3 === str4);
// out('str4 === str4',str4 === str4);
// var dt = new Date("November 24, 2020 17:41:00");
// var ds = dt.toString();
// out('dt === ds',dt === ds);

// out('5 != 5',5 != 5);
// out('"apple" != "apple"',"apple" != "apple");
// out('"5" != 5',"5" != 5);
// out('5 != "5"',5 != "5");
// out('0 != false',0 != false);
// out('0 != null',0 != null);
// out('0 != undefined',0 != undefined);
// out('0 != !!null',0 != !!null);
// out('0 != !!undefined',0 != !!undefined);
// out('null != undefined',null != undefined);
// var number1 = new Number(2);
// var number2 = new Number(2);
// out('number1 != 2',number1 != 2);
// out('number1 != number2',number1 != number2);
// var obj1 = {name: "Bob"};
// var obj2 = {name: "Bob"};
// out('obj1 != obj2',obj1 != obj2);
// out('obj2 != obj2',obj2 != obj2);
// var str1 = "orange";
// var str2 = String("orange");
// var str3 = new String("orange");
// var str4 = new String("orange");
// out('str1 != str2',str1 != str2);
// out('str1 != str3',str1 != str3);
// out('str2 != str3',str2 != str3);
// out('str3 != str4',str3 != str4);
// out('str4 != str4',str4 != str4);
// var dt = new Date("November 24, 2020 17:41:00");
// var ds = dt.toString();
// out('dt != ds',dt != ds);

// out('5 !== 5',5 !== 5);
// out('"apple" !== "apple"',"apple" !== "apple");
// out('"5" !== 5',"5" !== 5);
// out('5 !== "5"',5 !== "5");
// out('0 !== false',0 !== false);
// out('0 !== null',0 !== null);
// out('0 !== undefined',0 !== undefined);
// out('0 !== !!null',0 !== !!null);
// out('0 !== !!undefined',0 !== !!undefined);
// out('null !== undefined',null !== undefined);
// var number1 = new Number(2);
// var number2 = new Number(2);
// out('number1 !== 2',number1 !== 2);
// out('number1 !== number2',number1 !== number2);
// var obj1 = {name: "Bob"};
// var obj2 = {name: "Bob"};
// out('obj1 !== obj2',obj1 !== obj2);
// out('obj2 !== obj2',obj2 !== obj2);
// var str1 = "orange";
// var str2 = String("orange");
// var str3 = new String("orange");
// var str4 = new String("orange");
// out('str1 !== str2',str1 !== str2);
// out('str1 !== str3',str1 !== str3);
// out('str2 !== str3',str2 !== str3);
// out('str3 !== str4',str3 !== str4);
// out('str4 !== str4',str4 !== str4);
// var dt = new Date("November 24, 2020 17:41:00");
// var ds = dt.toString();
// out('dt !== ds',dt !== ds);

out('"a" > "b"',"a" > "b");
out('"a" > "a"',"a" > "a");
out('"a" > "3"',"a" > "3");
out('"5" > 3',"5" > 3);
out('"3" > 3',"3" > 3);
out('"3" > 5',"3" > 5);
out('5 > 3',5 > 3);
out('3 > 3',3 > 3);
out('3 > 5',3 > 5);
out('5n > 3',5n > 3);
out('3 > 5n',3 > 5n);
out('true > false',true > false);
out('false > 0',false > 0);
out('null > 0',null > 0);
out('undefined > 3',undefined > 3);
out('3 > undefined',3 > undefined);

out('"a" < "b"',"a" < "b");
out('"a" < "a"',"a" < "a");
out('"a" < "3"',"a" < "3");
out('"5" < 3',"5" < 3);
out('"3" < 3',"3" < 3);
out('"3" < 5',"3" < 5);
out('5 < 3',5 < 3);
out('3 < 3',3 < 3);
out('3 < 5',3 < 5);
out('5n < 3',5n < 3);
out('3 < 5n',3 < 5n);
out('true < false',true < false);
out('false < 0',false < 0);
out('null < 0',null < 0);
out('undefined < 3',undefined < 3);
out('3 < undefined',3 < undefined);