// console.log(+3);
// console.log(+"-3");
// console.log(+"3");
// console.log(+"0xFF");
// console.log(+true);
// console.log(+"123e-5");
// console.log(+false);
// console.log(+null);
// console.log(+"Infinity");
// console.log(+"infinity");
// console.log(+function(val){ return val });

console.log(-3);
console.log(-"-3");
console.log(-"3");
console.log(-"0xFF");
console.log(-true);
console.log(-"123e-5");
console.log(-false);
console.log(-null);
console.log(-"Infinity");
console.log(-"infinity");
console.log(-function(val){ return val });